//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergiaEnRuta
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="ENR-WS-REGISTER-SALEPortType", Namespace="enr.energia_en_ruta.com", ConfigurationName="EnergiaEnRuta.ENRWSREGISTERSALEPortType")]
    public interface ENRWSREGISTERSALEPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://3.236.155.113/energia-en-ruta-test/public/index.php/RegistrarVentaCombusti" +
            "ble", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FormaPago))]
        EnergiaEnRuta.RegistrarVentaCombustibleResponse RegistrarVentaCombustible(EnergiaEnRuta.RegistrarVentaCombustibleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://3.236.155.113/energia-en-ruta-test/public/index.php/RegistrarVentaCombusti" +
            "ble", ReplyAction="*")]
        System.Threading.Tasks.Task<EnergiaEnRuta.RegistrarVentaCombustibleResponse> RegistrarVentaCombustibleAsync(EnergiaEnRuta.RegistrarVentaCombustibleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://3.236.155.113/energia-en-ruta-test/public/index.php/SolicitarAutorizacionC" +
            "redito", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FormaPago))]
        EnergiaEnRuta.SolicitarAutorizacionCreditoResponse SolicitarAutorizacionCredito(EnergiaEnRuta.SolicitarAutorizacionCreditoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://3.236.155.113/energia-en-ruta-test/public/index.php/SolicitarAutorizacionC" +
            "redito", ReplyAction="*")]
        System.Threading.Tasks.Task<EnergiaEnRuta.SolicitarAutorizacionCreditoResponse> SolicitarAutorizacionCreditoAsync(EnergiaEnRuta.SolicitarAutorizacionCreditoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="enr.energia_en_ruta.com")]
    public partial class solicitud_registro_venta
    {
        
        private string codigoEDSField;
        
        private int idTurnoHorarioField;
        
        private int idCorteTVField;
        
        private string numeroDocumentoField;
        
        private string identificacionVendedorField;
        
        private double totalVentaField;
        
        private string numeroIdentificadorField;
        
        private int idAutorizacionField;
        
        private FormaPago[] formasPagoField;
        
        private DetalleVentaMaterial detalleVentaMaterialField;
        
        private string codigoPosicionField;
        
        private int idTurnoField;
        
        private bool ventaManualField;
        
        private System.DateTime fechaHoraInicioField;
        
        private System.DateTime fechaHoraFinField;
        
        private double lecturaInicialField;
        
        private double lecturaFinalField;
        
        private string placaField;
        
        private double kilometrajeField;
        
        private string numeroManifiestoField;
        
        private double precioVentaClienteField;
        
        private double precioVentaEDSField;
        
        /// <remarks/>
        public string CodigoEDS
        {
            get
            {
                return this.codigoEDSField;
            }
            set
            {
                this.codigoEDSField = value;
            }
        }
        
        /// <remarks/>
        public int IdTurnoHorario
        {
            get
            {
                return this.idTurnoHorarioField;
            }
            set
            {
                this.idTurnoHorarioField = value;
            }
        }
        
        /// <remarks/>
        public int IdCorteTV
        {
            get
            {
                return this.idCorteTVField;
            }
            set
            {
                this.idCorteTVField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroDocumento
        {
            get
            {
                return this.numeroDocumentoField;
            }
            set
            {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string IdentificacionVendedor
        {
            get
            {
                return this.identificacionVendedorField;
            }
            set
            {
                this.identificacionVendedorField = value;
            }
        }
        
        /// <remarks/>
        public double TotalVenta
        {
            get
            {
                return this.totalVentaField;
            }
            set
            {
                this.totalVentaField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroIdentificador
        {
            get
            {
                return this.numeroIdentificadorField;
            }
            set
            {
                this.numeroIdentificadorField = value;
            }
        }
        
        /// <remarks/>
        public int IdAutorizacion
        {
            get
            {
                return this.idAutorizacionField;
            }
            set
            {
                this.idAutorizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public FormaPago[] FormasPago
        {
            get
            {
                return this.formasPagoField;
            }
            set
            {
                this.formasPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public DetalleVentaMaterial DetalleVentaMaterial
        {
            get
            {
                return this.detalleVentaMaterialField;
            }
            set
            {
                this.detalleVentaMaterialField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoPosicion
        {
            get
            {
                return this.codigoPosicionField;
            }
            set
            {
                this.codigoPosicionField = value;
            }
        }
        
        /// <remarks/>
        public int IdTurno
        {
            get
            {
                return this.idTurnoField;
            }
            set
            {
                this.idTurnoField = value;
            }
        }
        
        /// <remarks/>
        public bool VentaManual
        {
            get
            {
                return this.ventaManualField;
            }
            set
            {
                this.ventaManualField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaHoraInicio
        {
            get
            {
                return this.fechaHoraInicioField;
            }
            set
            {
                this.fechaHoraInicioField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaHoraFin
        {
            get
            {
                return this.fechaHoraFinField;
            }
            set
            {
                this.fechaHoraFinField = value;
            }
        }
        
        /// <remarks/>
        public double LecturaInicial
        {
            get
            {
                return this.lecturaInicialField;
            }
            set
            {
                this.lecturaInicialField = value;
            }
        }
        
        /// <remarks/>
        public double LecturaFinal
        {
            get
            {
                return this.lecturaFinalField;
            }
            set
            {
                this.lecturaFinalField = value;
            }
        }
        
        /// <remarks/>
        public string Placa
        {
            get
            {
                return this.placaField;
            }
            set
            {
                this.placaField = value;
            }
        }
        
        /// <remarks/>
        public double Kilometraje
        {
            get
            {
                return this.kilometrajeField;
            }
            set
            {
                this.kilometrajeField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroManifiesto
        {
            get
            {
                return this.numeroManifiestoField;
            }
            set
            {
                this.numeroManifiestoField = value;
            }
        }
        
        /// <remarks/>
        public double PrecioVentaCliente
        {
            get
            {
                return this.precioVentaClienteField;
            }
            set
            {
                this.precioVentaClienteField = value;
            }
        }
        
        /// <remarks/>
        public double PrecioVentaEDS
        {
            get
            {
                return this.precioVentaEDSField;
            }
            set
            {
                this.precioVentaEDSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="enr.energia_en_ruta.com")]
    public partial class FormaPago
    {
        
        private int codigoSAPField;
        
        private int codigoSAPNuevoField;
        
        private string nombreField;
        
        private double valorField;
        
        private string numeroComprobanteField;
        
        private string numeroAprobacionField;
        
        private string numeroDocumentoField;
        
        /// <remarks/>
        public int CodigoSAP
        {
            get
            {
                return this.codigoSAPField;
            }
            set
            {
                this.codigoSAPField = value;
            }
        }
        
        /// <remarks/>
        public int CodigoSAPNuevo
        {
            get
            {
                return this.codigoSAPNuevoField;
            }
            set
            {
                this.codigoSAPNuevoField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public double Valor
        {
            get
            {
                return this.valorField;
            }
            set
            {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroComprobante
        {
            get
            {
                return this.numeroComprobanteField;
            }
            set
            {
                this.numeroComprobanteField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroAprobacion
        {
            get
            {
                return this.numeroAprobacionField;
            }
            set
            {
                this.numeroAprobacionField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroDocumento
        {
            get
            {
                return this.numeroDocumentoField;
            }
            set
            {
                this.numeroDocumentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="enr.energia_en_ruta.com")]
    public partial class DetalleMaterialCredito
    {
        
        private string codigoMaterialField;
        
        private System.Nullable<double> precioField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string CodigoMaterial
        {
            get
            {
                return this.codigoMaterialField;
            }
            set
            {
                this.codigoMaterialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> Precio
        {
            get
            {
                return this.precioField;
            }
            set
            {
                this.precioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="enr.energia_en_ruta.com")]
    public partial class Detalles
    {
        
        private DetalleMaterialCredito detalleMaterialCreditoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public DetalleMaterialCredito DetalleMaterialCredito
        {
            get
            {
                return this.detalleMaterialCreditoField;
            }
            set
            {
                this.detalleMaterialCreditoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="enr.energia_en_ruta.com")]
    public partial class Consumo
    {
        
        private System.Nullable<double> diaField;
        
        private System.Nullable<double> semanaField;
        
        private System.Nullable<double> mesField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> Dia
        {
            get
            {
                return this.diaField;
            }
            set
            {
                this.diaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> Semana
        {
            get
            {
                return this.semanaField;
            }
            set
            {
                this.semanaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> Mes
        {
            get
            {
                return this.mesField;
            }
            set
            {
                this.mesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="enr.energia_en_ruta.com")]
    public partial class Visita
    {
        
        private System.Nullable<int> diaField;
        
        private System.Nullable<int> semanaField;
        
        private System.Nullable<int> mesField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> Dia
        {
            get
            {
                return this.diaField;
            }
            set
            {
                this.diaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> Semana
        {
            get
            {
                return this.semanaField;
            }
            set
            {
                this.semanaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> Mes
        {
            get
            {
                return this.mesField;
            }
            set
            {
                this.mesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="enr.energia_en_ruta.com")]
    public partial class respuesta_solicitud_autorizacion
    {
        
        private System.Nullable<int> tipoField;
        
        private System.Nullable<int> idAutorizacionField;
        
        private string codigoClienteField;
        
        private string nombreClienteField;
        
        private string placaField;
        
        private System.Nullable<double> cupoField;
        
        private System.Nullable<double> saldoField;
        
        private string mensajeField;
        
        private Visita visitaField;
        
        private Consumo consumoField;
        
        private Detalles detallesField;
        
        private System.Nullable<double> descuentoField;
        
        private System.Nullable<double> precioVentaClienteField;
        
        private System.Nullable<double> precioVentaEDSField;
        
        private System.Nullable<bool> imprimirGuiaDespachoField;
        
        private System.Nullable<bool> usaManifiestoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> Tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdAutorizacion
        {
            get
            {
                return this.idAutorizacionField;
            }
            set
            {
                this.idAutorizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string CodigoCliente
        {
            get
            {
                return this.codigoClienteField;
            }
            set
            {
                this.codigoClienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string NombreCliente
        {
            get
            {
                return this.nombreClienteField;
            }
            set
            {
                this.nombreClienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Placa
        {
            get
            {
                return this.placaField;
            }
            set
            {
                this.placaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> Cupo
        {
            get
            {
                return this.cupoField;
            }
            set
            {
                this.cupoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> Saldo
        {
            get
            {
                return this.saldoField;
            }
            set
            {
                this.saldoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Visita Visita
        {
            get
            {
                return this.visitaField;
            }
            set
            {
                this.visitaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Consumo Consumo
        {
            get
            {
                return this.consumoField;
            }
            set
            {
                this.consumoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Detalles Detalles
        {
            get
            {
                return this.detallesField;
            }
            set
            {
                this.detallesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> Descuento
        {
            get
            {
                return this.descuentoField;
            }
            set
            {
                this.descuentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> PrecioVentaCliente
        {
            get
            {
                return this.precioVentaClienteField;
            }
            set
            {
                this.precioVentaClienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> PrecioVentaEDS
        {
            get
            {
                return this.precioVentaEDSField;
            }
            set
            {
                this.precioVentaEDSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<bool> ImprimirGuiaDespacho
        {
            get
            {
                return this.imprimirGuiaDespachoField;
            }
            set
            {
                this.imprimirGuiaDespachoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<bool> UsaManifiesto
        {
            get
            {
                return this.usaManifiestoField;
            }
            set
            {
                this.usaManifiestoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="enr.energia_en_ruta.com")]
    public partial class solicitud_autorizacion
    {
        
        private string codigoEDSField;
        
        private string tipoIdentificadorField;
        
        private string numeroIdentificadorField;
        
        private string manifiestoField;
        
        private int codigoPosicionField;
        
        private string placaField;
        
        private decimal kilometrajeField;
        
        private string codigoMaterialField;
        
        private bool requiereAprobacionField;
        
        private string fechaSolicitudField;
        
        /// <remarks/>
        public string CodigoEDS
        {
            get
            {
                return this.codigoEDSField;
            }
            set
            {
                this.codigoEDSField = value;
            }
        }
        
        /// <remarks/>
        public string TipoIdentificador
        {
            get
            {
                return this.tipoIdentificadorField;
            }
            set
            {
                this.tipoIdentificadorField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroIdentificador
        {
            get
            {
                return this.numeroIdentificadorField;
            }
            set
            {
                this.numeroIdentificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Manifiesto
        {
            get
            {
                return this.manifiestoField;
            }
            set
            {
                this.manifiestoField = value;
            }
        }
        
        /// <remarks/>
        public int CodigoPosicion
        {
            get
            {
                return this.codigoPosicionField;
            }
            set
            {
                this.codigoPosicionField = value;
            }
        }
        
        /// <remarks/>
        public string Placa
        {
            get
            {
                return this.placaField;
            }
            set
            {
                this.placaField = value;
            }
        }
        
        /// <remarks/>
        public decimal Kilometraje
        {
            get
            {
                return this.kilometrajeField;
            }
            set
            {
                this.kilometrajeField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoMaterial
        {
            get
            {
                return this.codigoMaterialField;
            }
            set
            {
                this.codigoMaterialField = value;
            }
        }
        
        /// <remarks/>
        public bool RequiereAprobacion
        {
            get
            {
                return this.requiereAprobacionField;
            }
            set
            {
                this.requiereAprobacionField = value;
            }
        }
        
        /// <remarks/>
        public string FechaSolicitud
        {
            get
            {
                return this.fechaSolicitudField;
            }
            set
            {
                this.fechaSolicitudField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="enr.energia_en_ruta.com")]
    public partial class respuesta_solicitud_registro_venta
    {
        
        private string mensajeField;
        
        private string estadoField;
        
        private System.Nullable<int> respuestaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> Respuesta
        {
            get
            {
                return this.respuestaField;
            }
            set
            {
                this.respuestaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="enr.energia_en_ruta.com")]
    public partial class DetalleVentaMaterial
    {
        
        private string codigoMaterialField;
        
        private double cantidadField;
        
        private double precioField;
        
        private double totalField;
        
        /// <remarks/>
        public string CodigoMaterial
        {
            get
            {
                return this.codigoMaterialField;
            }
            set
            {
                this.codigoMaterialField = value;
            }
        }
        
        /// <remarks/>
        public double Cantidad
        {
            get
            {
                return this.cantidadField;
            }
            set
            {
                this.cantidadField = value;
            }
        }
        
        /// <remarks/>
        public double Precio
        {
            get
            {
                return this.precioField;
            }
            set
            {
                this.precioField = value;
            }
        }
        
        /// <remarks/>
        public double Total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarVentaCombustible", WrapperNamespace="enr.energia_en_ruta.com", IsWrapped=true)]
    public partial class RegistrarVentaCombustibleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public EnergiaEnRuta.solicitud_registro_venta name;
        
        public RegistrarVentaCombustibleRequest()
        {
        }
        
        public RegistrarVentaCombustibleRequest(EnergiaEnRuta.solicitud_registro_venta name)
        {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarVentaCombustibleResponse", WrapperNamespace="enr.energia_en_ruta.com", IsWrapped=true)]
    public partial class RegistrarVentaCombustibleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public EnergiaEnRuta.respuesta_solicitud_registro_venta name;
        
        public RegistrarVentaCombustibleResponse()
        {
        }
        
        public RegistrarVentaCombustibleResponse(EnergiaEnRuta.respuesta_solicitud_registro_venta name)
        {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SolicitarAutorizacionCredito", WrapperNamespace="enr.energia_en_ruta.com", IsWrapped=true)]
    public partial class SolicitarAutorizacionCreditoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public EnergiaEnRuta.solicitud_autorizacion name;
        
        public SolicitarAutorizacionCreditoRequest()
        {
        }
        
        public SolicitarAutorizacionCreditoRequest(EnergiaEnRuta.solicitud_autorizacion name)
        {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SolicitarAutorizacionCreditoResponse", WrapperNamespace="enr.energia_en_ruta.com", IsWrapped=true)]
    public partial class SolicitarAutorizacionCreditoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public EnergiaEnRuta.respuesta_solicitud_autorizacion name;
        
        public SolicitarAutorizacionCreditoResponse()
        {
        }
        
        public SolicitarAutorizacionCreditoResponse(EnergiaEnRuta.respuesta_solicitud_autorizacion name)
        {
            this.name = name;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ENRWSREGISTERSALEPortTypeChannel : EnergiaEnRuta.ENRWSREGISTERSALEPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ENRWSREGISTERSALEPortTypeClient : System.ServiceModel.ClientBase<EnergiaEnRuta.ENRWSREGISTERSALEPortType>, EnergiaEnRuta.ENRWSREGISTERSALEPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ENRWSREGISTERSALEPortTypeClient() : 
                base(ENRWSREGISTERSALEPortTypeClient.GetDefaultBinding(), ENRWSREGISTERSALEPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ENR_WS_REGISTER_SALEPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ENRWSREGISTERSALEPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(ENRWSREGISTERSALEPortTypeClient.GetBindingForEndpoint(endpointConfiguration), ENRWSREGISTERSALEPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ENRWSREGISTERSALEPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ENRWSREGISTERSALEPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ENRWSREGISTERSALEPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ENRWSREGISTERSALEPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ENRWSREGISTERSALEPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public EnergiaEnRuta.RegistrarVentaCombustibleResponse RegistrarVentaCombustible(EnergiaEnRuta.RegistrarVentaCombustibleRequest request)
        {
            return base.Channel.RegistrarVentaCombustible(request);
        }
        
        public System.Threading.Tasks.Task<EnergiaEnRuta.RegistrarVentaCombustibleResponse> RegistrarVentaCombustibleAsync(EnergiaEnRuta.RegistrarVentaCombustibleRequest request)
        {
            return base.Channel.RegistrarVentaCombustibleAsync(request);
        }
        
        public EnergiaEnRuta.SolicitarAutorizacionCreditoResponse SolicitarAutorizacionCredito(EnergiaEnRuta.SolicitarAutorizacionCreditoRequest request)
        {
            return base.Channel.SolicitarAutorizacionCredito(request);
        }
        
        public System.Threading.Tasks.Task<EnergiaEnRuta.SolicitarAutorizacionCreditoResponse> SolicitarAutorizacionCreditoAsync(EnergiaEnRuta.SolicitarAutorizacionCreditoRequest request)
        {
            return base.Channel.SolicitarAutorizacionCreditoAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ENR_WS_REGISTER_SALEPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ENR_WS_REGISTER_SALEPort))
            {
                return new System.ServiceModel.EndpointAddress("http://3.236.155.113/energia-en-ruta-test/public/index.php");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ENRWSREGISTERSALEPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.ENR_WS_REGISTER_SALEPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ENRWSREGISTERSALEPortTypeClient.GetEndpointAddress(EndpointConfiguration.ENR_WS_REGISTER_SALEPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ENR_WS_REGISTER_SALEPort,
        }
    }
}
